### PR TITLE
Add `mc-sgx-panic` crate

### PR DESCRIPTION
**Pull request by nick-mobilecoin**

### CODE REVIEW

**Comment by nick-mobilecoin** [comment]
Current dependencies on/for this PR:
* main
  * **PR #5** <a href="https://app.graphite.dev/github/pr/mobilecoinfoundation/sgx-std/5" target="_blank">Graphite</a> 
    * **PR #7** <a href="https://app.graphite.dev/github/pr/mobilecoinfoundation/sgx-std/7" target="_blank">Graphite</a> 
      * **PR #6** <a href="https://app.graphite.dev/github/pr/mobilecoinfoundation/sgx-std/6" target="_blank">Graphite</a> 
        * **PR #8** <a href="https://app.graphite.dev/github/pr/mobilecoinfoundation/sgx-std/8" target="_blank">Graphite</a> 
          * **PR #10** <a href="https://app.graphite.dev/github/pr/mobilecoinfoundation/sgx-std/10" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/mobilecoinfoundation/sgx-std/10?utm_source=stack-comment).

**Review by NotGyro — APPROVED** [review]
Looks good to me - first commit

**Review by jcape — APPROVED** [review]

**Comment by nick-mobilecoin** [comment]
**Graphite Merge Job**

Current status: ⏳ Queued to merge

This pull request is currently queued to be merged as part of a stack.

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/mobilecoinfoundation/sgx-std/10?utm_source=stack-comment).


Job Reference: 0ATuqwtRB8VWI35Z84LS

**Review by NotGyro — APPROVED** [review]
Looks good to me, tiny change since I reviewed this previously, should be fine.

**Pull request merged**
