### PR TITLE
Use stable rust toolchain by default

### PR DESCRIPTION
**Pull request by nick-mobilecoin**
Previously this repo was using nightly, it is now on stable.

Also added beta to some of the CI steps

### CODE REVIEW

**Comment by nick-mobilecoin** [comment]
Current dependencies on/for this PR:
* main
  * **PR #19** <a href="https://app.graphite.dev/github/pr/mobilecoinfoundation/sgx-std/19" target="_blank">Graphite</a> 
    * **PR #20** <a href="https://app.graphite.dev/github/pr/mobilecoinfoundation/sgx-std/20" target="_blank">Graphite</a> 
      * **PR #25** <a href="https://app.graphite.dev/github/pr/mobilecoinfoundation/sgx-std/25" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/mobilecoinfoundation/sgx-std/25?utm_source=stack-comment).

**Review by NotGyro — APPROVED** [review]
This looks good, should be okay to merge.

**Review by samdealy — APPROVED** [review]
LGTM thanks

**Comment by nick-mobilecoin** [comment]
@NotGyro or @samdealy if one of you could do another review then this can be merged.
I had to rebase due to a conflict that came in before this,
Thanks!

**Review by NotGyro — APPROVED** [review]
This still looks fine, approving the rebase

**Pull request merged**
