### PR TITLE
Add `RwLock` to `mc-sgx-sync`

### PR DESCRIPTION
**Pull request by nick-mobilecoin**

### CODE REVIEW

**Comment by nick-mobilecoin** [comment]
Current dependencies on/for this PR:
* main
  * **PR #14** <a href="https://app.graphite.dev/github/pr/mobilecoinfoundation/sgx-std/14" target="_blank">Graphite</a> 
    * **PR #13** <a href="https://app.graphite.dev/github/pr/mobilecoinfoundation/sgx-std/13" target="_blank">Graphite</a> 
      * **PR #15** <a href="https://app.graphite.dev/github/pr/mobilecoinfoundation/sgx-std/15" target="_blank">Graphite</a> 
        * **PR #22** <a href="https://app.graphite.dev/github/pr/mobilecoinfoundation/sgx-std/22" target="_blank">Graphite</a> 
          * **PR #24** <a href="https://app.graphite.dev/github/pr/mobilecoinfoundation/sgx-std/24" target="_blank">Graphite</a> 
            * **PR #30** <a href="https://app.graphite.dev/github/pr/mobilecoinfoundation/sgx-std/30" target="_blank">Graphite</a> 
              * **PR #31** <a href="https://app.graphite.dev/github/pr/mobilecoinfoundation/sgx-std/31" target="_blank">Graphite</a> 
                * **PR #32** <a href="https://app.graphite.dev/github/pr/mobilecoinfoundation/sgx-std/32" target="_blank">Graphite</a> 
                  * **PR #33** <a href="https://app.graphite.dev/github/pr/mobilecoinfoundation/sgx-std/33" target="_blank">Graphite</a> 
                    * **PR #34** <a href="https://app.graphite.dev/github/pr/mobilecoinfoundation/sgx-std/34" target="_blank">Graphite</a> 
                      * **PR #35** <a href="https://app.graphite.dev/github/pr/mobilecoinfoundation/sgx-std/35" target="_blank">Graphite</a> 
                        * **PR #36** <a href="https://app.graphite.dev/github/pr/mobilecoinfoundation/sgx-std/36" target="_blank">Graphite</a> 
                          * **PR #39** <a href="https://app.graphite.dev/github/pr/mobilecoinfoundation/sgx-std/39" target="_blank">Graphite</a> 
                            * **PR #40** <a href="https://app.graphite.dev/github/pr/mobilecoinfoundation/sgx-std/40" target="_blank">Graphite</a> 
                              * **PR #41** <a href="https://app.graphite.dev/github/pr/mobilecoinfoundation/sgx-std/41" target="_blank">Graphite</a> 
                                * **PR #42** <a href="https://app.graphite.dev/github/pr/mobilecoinfoundation/sgx-std/42" target="_blank">Graphite</a> 
                                  * **PR #43** <a href="https://app.graphite.dev/github/pr/mobilecoinfoundation/sgx-std/43" target="_blank">Graphite</a> 
                                    * **PR #44** <a href="https://app.graphite.dev/github/pr/mobilecoinfoundation/sgx-std/44" target="_blank">Graphite</a> 
                                      * **PR #45** <a href="https://app.graphite.dev/github/pr/mobilecoinfoundation/sgx-std/45" target="_blank">Graphite</a>  👈
        * **PR #21** <a href="https://app.graphite.dev/github/pr/mobilecoinfoundation/sgx-std/21" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/mobilecoinfoundation/sgx-std/45?utm_source=stack-comment).

**Review by samdealy — APPROVED** [review]

**Review by NotGyro — APPROVED** [review]
This looks fine to me, the one failing test is that `coverage` can't find `mc-sgx-tstdc` which looks like it's most likely just testing-environment flakiness. Should be good.

**Comment by nick-mobilecoin** [comment]
⏳ This pull request is set to merge as part of a Graphite merge job
Stack job ID: uCoNH97G95Be2subCEb9.
See details on [graphite.dev](https://app.graphite.dev/github/pr/mobilecoinfoundation/sgx-std/45)

**Comment by nick-mobilecoin** [comment]
@samdealy bumped you for re-review due to restack

**Review by samdealy — APPROVED** [review]

**Pull request merged**
